(cl:in-package calypso-msg)
(cl:export '(BUTTON1-VAL
          BUTTON1
          BUTTON2-VAL
          BUTTON2
          BUTTON3-VAL
          BUTTON3
          BUTTON4-VAL
          BUTTON4
          BUTTON5-VAL
          BUTTON5
          BUTTON6-VAL
          BUTTON6
          BUTTON7-VAL
          BUTTON7
          BUTTON8-VAL
          BUTTON8
          BUTTON9-VAL
          BUTTON9
          BUTTON10-VAL
          BUTTON10
          BUTTON11-VAL
          BUTTON11
          BUTTON12-VAL
          BUTTON12
          BUTTON13-VAL
          BUTTON13
          BUTTON14-VAL
          BUTTON14
          BUTTON15-VAL
          BUTTON15
          BUTTON16-VAL
          BUTTON16
          AXIS1-VAL
          AXIS1
          AXIS2-VAL
          AXIS2
          AXIS3-VAL
          AXIS3
          AXIS4-VAL
          AXIS4
))